# Generated by Django 5.0.1 on 2024-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('permission', models.CharField(choices=[('public', 'non authenticated can read'), ('authenticated', 'authenticated can read'), ('team', 'team members can read'), ('author', 'author can read')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
